library(isdals)
data(bodyfat)
help(bodyfat)
attach(bodyfat)
pairs(cbind(Fat, Triceps, Thigh, Midarm))
cor(cbind(Fat, Triceps, Thigh, Midarm))
fat.hat = predict(lm(Fat~Thigh))
triceps.hat = predict(lm(Triceps~Thigh))
cor((Fat - fat.hat), (Triceps - triceps.hat))
library(ppcor)
pcor(cbind(Fat, Triceps, Thigh))
